export { scaffold, substitute } from './scaffold';
export type { ScaffoldOptions } from './scaffold';
export { addPanel } from './panel/add';
export type { AddPanelOptions, AddPanelResult } from './panel/add';
export { addMenu } from './menu/add';
export type { AddMenuOptions, AddMenuResult } from './menu/add';
export { addCommand } from './command/add';
export type { AddCommandOptions, AddCommandResult } from './command/add';
export { addRpcMethod } from './rpc/add';
export type { AddRpcMethodOptions, AddRpcMethodResult } from './rpc/add';
export { addStatusBar } from './statusBar/add';
export type { AddStatusBarOptions, AddStatusBarResult } from './statusBar/add';
export { editMenu, listMenus, listPanels, listCommands, listGroups } from './menu/edit';
export type { EditMenuOptions, EditMenuResult, NewMenuItem, MenuItemKind } from './menu/edit';
export { runDoctor, applyFixes } from './doctor';
export type { CheckResult, DoctorReport, CheckLevel } from './doctor';
export { upgrade } from './upgrade';
export type { UpgradeOptions, UpgradeResult, FileChange } from './upgrade';
export { findProjectRoot, findTemplatesRoot } from './findProject';
