import * as fs from 'fs';
import * as path from 'path';

export interface ParsedRelation {
  /** FK field on this model (e.g. `categoryId`). */
  field: string;
  /** Related model name (e.g. `Category`). */
  model: string;
  /** Field on the related model to show in the picker. */
  label?: string;
}

export interface ParsedField {
  name: string;
  /** Raw TS type as written in the interface (e.g. `string`, `number`, `'a' | 'b'`, `Date`). */
  type: string;
  optional: boolean;
  /** Set when this field is a foreign key declared via `<Name>Relations`. */
  relation?: ParsedRelation;
}

export interface ParsedModel {
  /** PascalCase interface name. */
  name: string;
  /** camelCase id (file basename of the model file). */
  id: string;
  /** Plural identifier (e.g. `Users`). */
  plural: string;
  /** Collection name passed to defineEntity (e.g. `'users'`). */
  collection: string;
  /** Field declared as primaryKey in defineEntity call. */
  primaryKey: string;
  /** Field names listed in indexes (may be empty). */
  indexes: string[];
  /** Ordered field list from the interface body. */
  fields: ParsedField[];
  /** FK field → relation metadata, keyed by FK field name. */
  relations: Record<string, ParsedRelation>;
  /** Absolute path the model was read from. */
  path: string;
}

export function parseModelFile(file: string): ParsedModel {
  if (!fs.existsSync(file)) throw new Error(`Model file not found: ${file}`);
  const src = fs.readFileSync(file, 'utf8');

  const ifaceMatch = /export\s+interface\s+([A-Z][A-Za-z0-9_]*)\s*\{([\s\S]*?)\n\}/.exec(src);
  if (!ifaceMatch) {
    throw new Error(`Model "${path.basename(file)}" does not declare \`export interface\`.`);
  }
  const name = ifaceMatch[1];
  const body = ifaceMatch[2];
  const fields = parseInterfaceBody(body);
  if (fields.length === 0) {
    throw new Error(`Model "${name}" has no fields — add at least one before generating CRUD.`);
  }

  const pluralMatch = /export\s+const\s+([A-Z][A-Za-z0-9_]*)\s*=\s*defineEntity\s*<\s*[^>]+>\s*\(\s*(['"`])([^'"`]+)\2\s*,\s*\{([\s\S]*?)\}\s*\)/m.exec(src);
  if (!pluralMatch) {
    throw new Error(`Model "${name}" does not call \`defineEntity\`. Was it generated by \`vsceasy model add\`?`);
  }
  const plural = pluralMatch[1];
  const collection = pluralMatch[3];
  const entityBody = pluralMatch[4];

  const pk = /\bprimaryKey\s*:\s*(['"`])([^'"`]+)\1/.exec(entityBody)?.[2];
  if (!pk) throw new Error(`Model "${name}" defineEntity is missing primaryKey.`);

  const indexes: string[] = [];
  const idxMatch = /\bindexes\s*:\s*\[([^\]]*)\]/.exec(entityBody);
  if (idxMatch) {
    const inner = idxMatch[1];
    const re = /['"`]([^'"`]+)['"`]/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(inner))) indexes.push(m[1]);
  }

  const id = path.basename(file).replace(/\.(ts|tsx)$/, '');

  // Relation metadata: `export const <Name>Relations = { categoryId: { model: 'Category', label: 'name' }, ... }`
  const relations = parseRelations(src, name);
  for (const f of fields) {
    const r = relations[f.name];
    if (r) f.relation = r;
  }

  return { name, id, plural, collection, primaryKey: pk, indexes, fields, relations, path: file };
}

function parseRelations(src: string, name: string): Record<string, ParsedRelation> {
  const out: Record<string, ParsedRelation> = {};
  const block = new RegExp(`export\\s+const\\s+${name}Relations\\s*=\\s*\\{([\\s\\S]*?)\\}\\s*as\\s+const`, 'm').exec(src);
  if (!block) return out;
  const body = block[1];
  // each entry: `categoryId: { model: 'Category', label: 'name' },`
  const re = /([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\{\s*model\s*:\s*['"`]([^'"`]+)['"`]\s*(?:,\s*label\s*:\s*['"`]([^'"`]+)['"`]\s*)?\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(body))) {
    out[m[1]] = { field: m[1], model: m[2], label: m[3] };
  }
  return out;
}

/** Parse an interface body — fields are `name[?]: type;` (type may include `|`). */
function parseInterfaceBody(body: string): ParsedField[] {
  const fields: ParsedField[] = [];
  // Split on `;` or newline outside of <…>/(…)/[…] — simplest viable: scan line by line, trim trailing `;`
  const lines = body.split(/\n/).map((l) => l.trim()).filter(Boolean);
  for (const raw of lines) {
    if (raw.startsWith('//') || raw.startsWith('*') || raw.startsWith('/*')) continue;
    const line = raw.replace(/;$/, '').replace(/,$/, '').trim();
    if (!line) continue;
    const colon = line.indexOf(':');
    if (colon < 0) continue;
    let name = line.slice(0, colon).trim();
    const type = line.slice(colon + 1).trim();
    if (!name || !type) continue;
    let optional = false;
    if (name.endsWith('?')) {
      optional = true;
      name = name.slice(0, -1);
    }
    fields.push({ name, type, optional });
  }
  return fields;
}

/** Classify a TS field type into a UI input kind for the form generator. */
export type InputKind = 'text' | 'number' | 'boolean' | 'date' | 'select' | 'textarea';

export interface InputSpec {
  kind: InputKind;
  /** For `select`: literal values (`'a' | 'b'` → `['a','b']`). */
  options?: string[];
}

export function inferInputSpec(type: string): InputSpec {
  const t = type.trim();
  // strip `null | undefined` / `| null` etc.
  const cleaned = t
    .split('|')
    .map((p) => p.trim())
    .filter((p) => p !== 'null' && p !== 'undefined');

  if (cleaned.length > 1 && cleaned.every((p) => /^(['"`]).*\1$/.test(p))) {
    return { kind: 'select', options: cleaned.map((p) => p.slice(1, -1)) };
  }
  const single = cleaned[0] ?? t;
  if (/^number$/.test(single)) return { kind: 'number' };
  if (/^boolean$/.test(single)) return { kind: 'boolean' };
  if (/^Date$/.test(single)) return { kind: 'date' };
  // string with hints — textarea for fields likely to be long
  if (/^string$/.test(single)) return { kind: 'text' };
  // fallback
  return { kind: 'text' };
}
