#!/usr/bin/env bun
/**
 * Embeds the entire templates/ tree into a generated TS module so the compiled
 * CLI carries its templates inside the bundle. Required because a globally
 * installed binary (e.g. `bun add -g`) resolves through a symlinked bin path
 * and can never walk the filesystem up to the package's templates/ dir.
 *
 * Output: src/lib/templatesData.ts — a flat map of POSIX-relative path → file
 * contents. At runtime findTemplatesRoot() materializes this to a temp dir, so
 * every existing fs-based consumer keeps working unchanged.
 *
 * Run from package.json `build` AFTER sync:runtime (which mutates templates/)
 * and BEFORE the bundle step.
 */
import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const TEMPLATES = path.join(ROOT, 'templates');
const OUT = path.join(ROOT, 'src', 'lib', 'templatesData.ts');

const SKIP_NAMES = new Set(['node_modules', 'dist', '.DS_Store']);

if (!fs.existsSync(TEMPLATES)) {
  console.error(`✗ templates/ missing at ${TEMPLATES}`);
  process.exit(1);
}

const entries: Array<[string, string]> = [];

function walk(dir: string) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_NAMES.has(ent.name)) continue;
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      walk(abs);
    } else if (ent.isFile()) {
      // POSIX-relative key so it is stable across platforms.
      const rel = path.relative(TEMPLATES, abs).split(path.sep).join('/');
      const content = fs.readFileSync(abs, 'utf8');
      entries.push([rel, content]);
    }
  }
}

walk(TEMPLATES);
entries.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

const version: string = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'),
).version;

const body = entries
  .map(([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/embedTemplates.ts — do not edit.
// Flat map of POSIX-relative template path -> file contents. Materialized to a
// temp dir at runtime by findTemplatesRoot(). Regenerate via \`bun run build\`.
/* eslint-disable */
export const TEMPLATES_VERSION = ${JSON.stringify(version)};
export const TEMPLATE_FILES: Record<string, string> = {
${body}
};
`;

fs.writeFileSync(OUT, out);
console.log(`✓ embedded ${entries.length} template file(s) → src/lib/templatesData.ts`);
