#!/usr/bin/env bun
/**
 * Generates the CodiconName type union from src/data/codicons.ts.
 * Writes to:
 *   - templates/react/src/shared/vsxf/codiconNames.ts   (scaffolded into new projects)
 *
 * Run via `bun run gen:types` whenever src/data/codicons.ts changes.
 */
import * as fs from 'fs';
import * as path from 'path';
import { CODICONS } from '../src/data/codicons';

const repoRoot = path.resolve(__dirname, '..');
const targets = [
  path.join(repoRoot, 'templates/react/src/shared/vsxf/codiconNames.ts'),
];

const names = Array.from(new Set(CODICONS.map((c) => c.name))).sort();
const union = names.map((n) => `  | '${n}'`).join('\n');

const body = `/**
 * AUTO-GENERATED by scripts/genCodiconTypes.ts — do not edit.
 *
 * Curated subset of VS Code codicon names that the CLI's icon picker offers.
 * Used by \`MenuIcon\` for editor autocomplete. Any string is still accepted at
 * runtime via the \`(string & {})\` fallback in define.ts.
 *
 * Full list: https://microsoft.github.io/vscode-codicons/dist/codicon.html
 */
export type CodiconName =
${union};
`;

for (const target of targets) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, body);
  console.log(`✓ wrote ${path.relative(repoRoot, target)} (${names.length} names)`);
}
